config/routes.rb
Rails.application.routes.draw do
  resources :sub_categories
  devise_for :users
  resources :homeworks
  resources :categories
  root "homeworks#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/homework.rb
class Homework < ApplicationRecord
    belongs_to :created_by, class_name: 'User', optional: true 
    #membuat relasi created_by dengan class 'user'
    
    validates :homework_name, presence: true
    validates :category, presence: true
    validates :deadline, presence: true
    validates :description, presence: true, length: {maximum:300}
  
    validate :deadline_cannot_be_in_the_past
    belongs_to :category
  
    #contoh custom validation untuk melakukan validasi
    #bahwa deadline tidak boleh terjadi di masa lampauu
    def deadline_cannot_be_in_the_past
      errors.add(:deadline, "can't be in the past") if
      deadline < Date.today
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:show, :edit, :destroy]
  before_action :set_user, only: [ :show, :update, :delete ]
    
  # GET /homeworks
  # GET /homeworks.json
  def index 
    @homeworks = Homework.where(["homework_name LIKE ?","%#{params[:search]}%"])
  
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
    
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
    @category = Category.all
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)
    
    respond_to do |format|
      if @homework.save #jika data berhasil disimpan
         @homework.update(created_by_id: current_user.id) 
         format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
         #menuju ke halaman show data dan menampilkan pesan "Homework was successfully created"
        
        format.json { render :show, status: :created, location: @homework }
      else #jika data tidak berhasil disimpan
        format.html { render :new }  
        #kembali ke halaman tambah data homework
        
        format.json { render json: @homework.errors, status: :unprocessable_entity }
        #memunculkan pesan error dalam bentuk json. Perhatikan bagian "@homework.errors"
      end
  end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def filtering_params(params)
      params.slice(:status, :location, :starts_with)
    end
    def set_user
      @user =User.new
    end
   
    def set_categories
      @category =Category.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:homework_name, :category, :deadline, :description, :category_id, :destroy )
    end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/_form.html.erb
<%= form_with(model: homework, local: true) do |form| %>
  <% if homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
        <% homework.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <br>
 <center><h6>
  <div class="field">
      <%= form.label :homework_name %><br>
      <%= form.text_area :homework_name, id: :homework_homework_category %>
    </div>
    <br>
  <div class="field">
      <%= form.label :category %><br>
        <% if @homework.category.present? %>
      <%= select_tag 'homework[category_id]', options_for_select(@category.collect { |c| [c.name, c.id] }, {:selected => @homework.category.id}) %>
        <% else %>
      <%= select_tag 'homework[category_id]', options_for_select(@category.collect { |c| [c.name, c.id] }) %>
    <% end %>
    
</div>
<br>

  <div class="field"> 
    <%= form.label :deadline %><br>
    <%= form.date_select :deadline, id: :homework_deadline %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, id: :homework_description %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
    </h6>
  </div>
  
<% end %>
</center>

app/views/homeworks/_navigation.html.erb
<p class="btn btn-outline-">
  <% if user_signed_in? %>
    <strong><%= current_user.email %></strong> <br>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
      <%= button_to "Log out", destroy_user_session_path, method: :delete  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> ||
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  <center>
  <br>
  <ul class="btn btn-outline-light">
    <li class="active"><%= link_to 'Homework', homeworks_path, :class => 'navbar-link' %> 
  </ul>  

  <ul class="btn btn-outline-light">
    <li class="active"><%= link_to 'Category', categories_path, :class => 'navbar-link' %>
  </li>
</ul>

app/views/homeworks/edit.html.erb
<center>
<div class="p-3 mb-2 bg-dark text-white">
<h1 class="text-primary">Editing Homework</h1>
<%= render 'form', homework: @homework %>


<%= link_to 'Show', @homework %> 
<%= link_to 'Back', homeworks_path %>
</div>

</center>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="p-3 mb-2 bg-light text-dark">
    <nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
  <h1 class="text-dark">Homework</h1>
  </nav>
  <%= form_tag homeworks_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "search"%>
       <% end %>
  
<h5><%= render 'navigation'%></h5>
<center>
<table class="table table-dark">
  <thead>
    <tr>
      <th>Homework name</th>
      <th>Category</th>
      <th>Deadline</th>
      <th>Description</th>
      <th>User<th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><h6><%= homework.homework_name %></h6></td>
        <td><h6><%= homework.category.try (:name)%></h6></td>
        <td><h6><%= homework.deadline %></h6></td>
        <td><h6><%= homework.description %></h6></td>
        <td><h6><%= homework.created_by.try(:email) %></h6></td>
        <td ><h6><%= link_to 'Show', homework %></h6></td><br>
        <td></td>
        <td ><h6><%= link_to 'Edit', edit_homework_path(homework) %></h6></td>
       <td><h6><%= button_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></h5></td>
      </tr>
    <% end %>
     <div class="btn btn-primary ">
    <%= link_to 'New Homework', new_homework_path %> 
</div>
  </tbody>
</table>
</div>

app/views/homeworks/new.html.erb
<div class="p-3 mb-2 bg-dark text-white">
<center>
<h1 class="text-primary">New Homework</h1>


<%= render 'form', homework: @homework %>
<%= link_to 'Back', homeworks_path %>
</center>

app/views/homeworks/show.html.erb
<div class="p-3 mb-2 bg-info text-white">
<center>
<br>
<h1 class="text-dark">Show </h1>
<p id="notice"><%= notice %></p>

<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
<p>
  <h6><strong>Homework name :</strong> <br>
    <%= @homework.homework_name %>
  </h6>
</p>
<p>
  <h6><strong>Category:</strong> <br>
    <%= @homework.category.try(:name) %>
  </h6>
</p>
<p>
<h6>
  <strong>Deadline:</strong><br>
    <%= @homework.deadline %>
  </h6>
</p>
<p>
<h6>
  <strong>Description:</strong><br>
    <%= @homework.description %>
  </h6>
</p>
<p>
<h6>
  <strong>Category:</strong>
  <%= @homework.category_id %>
  </h6>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> 
<%= link_to 'Back', homeworks_path %>
</div>
</center>